name: gmsl
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - pytorch-lightning=2.0.3
  - pip=23.0.1
  - pandas=2.0.3
  - openbabel=3.1.1
  - pip:
    - torch-geometric==2.3.1
    - torch-scatter==2.1.1
    - torchdrug==0.2.1
    - e3nn==0.5.1
    - atom3d==0.2.6
    - torch-sparse==0.6.17
    - easydict==1.10
    - wandb==0.15.8