# This is the config file for GearNet without Edge layers and Checkpoints.

# Lightning Model Settings
model_args:
  sdim: 128
  vdim: 16
  depth: 3
  aggr: 'mean'
  model_type: gearnet
  num_radial: 32
  learning_rate: 1.0e-4
  weight_decay: 0
  readout: task_aware_attention
  # [weighted_feature, task_aware_attention]
  r_cutoff: 4.5
  factor_scheduler: 0.75
  layer_norm: True
  batch_norm: True
  hidden_dims:
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
  embedding_dim: 512
  num_relation: 7

#Dataset Settings
batch_size: 64
drop_last: False
run_name: gearnet
train_task: multi
train_split: train_all
val_split: val
test_split: test
alpha_only: True
offset_strategy: 1
num_workers: 4
graph_cache_dir: ./datasets/MultiTask/processed_graphs/hetero_alpha_only_knn5_spatial4.5_sequential2

# Trainer Settings
device:
  - 1
  - 3
nruns: 3
wandb: False
save_dir: gearnet
gradient_clip_val: 10
load_ckpt: null
seed: 817
batch_accum_grad: 1
max_epochs: 50