# This is the config file for EQGAT.

# Lightning Model Settings
model_args:
  sdim: 256
  vdim: 16
  task: multi
  depth: 3
  aggr: 'mean'
  model_type: gp
  num_radial: 32
  embedding_dim: 256
  learning_rate: 1.0e-4
  weight_decay: 0
  readout: vallina
  r_cutoff: 4.5
  concat_hidden: False
  hidden_dims:
    - 256
    - 256
    - 256
  factor_scheduler: 0.75
  layer_norm: True
  batch_norm: True

#Dataset Settings
batch_size: 32
drop_last: False
run_name: gvp
train_split: train_all
val_split: val
test_split: test
alpha_only: False
offset_strategy: 1
num_workers: 4
graph_cache_dir: ./datasets/MultiTask_c03_id09/graphs_new/fullatom_knn9_spatial4.5_sequential2

# Trainer Settings
device:
  - 2
  - 3
nruns: 3
wandb: False
save_dir: gvp
gradient_clip_val: 10
batch_accum_grad: 1
load_ckpt: null
seed: 817
max_epochs: 30