# This is the config file for EGNN.

# Lightning Model Settings
batch_size: 32
sdim: 100
vdim: 16
depth: 3
model_type: egnn
num_radial: 32
learning_rate: 1.0e-4
batch_accum_grad: 1
weight_decay: 0
max_epochs: 50
enhanced: False
# 这些都是EQGAT需要的参数，之后优化掉
cross_ablate: False
no_feat_attn: False

#Dataset Settings
drop_last: False
run_name: egnn
train_task: multi
train_split: train_all
val_split: val
test_split: test
alpha_only: True
offset_strategy: 1
num_workers: 4

# Trainer Settings
device: 
  - 3
nruns: 3
wandb: True
save_dir: egnn
gradient_clip_val: 10
load_ckpt: null
seed: 817