# This is the config file for EGNN.

# Lightning Model Settings
model_args:
  sdim: 128
  vdim: 16
  depth: 3
  aggr: 'mean'
  model_type: egnn
  num_radial: 32
  learning_rate: 1.0e-4
  weight_decay: 0
  readout: weighted_feature
  r_cutoff: 4.5
  factor_scheduler: 0.75
  layer_norm: True
  batch_norm: True

#Dataset Settings
batch_size: 32
drop_last: False
run_name: egnn
train_task: multi
train_split: train_all
val_split: val
test_split: test
alpha_only: False
offset_strategy: 1
num_workers: 28

# Trainer Settings
device:
  - 0
nruns: 3
wandb: False
save_dir: egnn
gradient_clip_val: 10
batch_accum_grad: 1
load_ckpt: null
seed: 817
max_epochs: 50