# This is the config file for Heterougeneous Multitask Equivariant Network (HemeNet).

# Lightning Model Settings
batch_size: 8
sdim: 128
vdim: 16
depth: 3
model_type: hemenet
num_radial: 32
learning_rate: 1.0e-4
batch_accum_grad: 1
weight_decay: 0
max_epochs: 50
graph_cache_dir: ./datasets/MultiTask/processed_graphs/hetero_fullatom_knn5_spatial4.5_sequential2
enhanced: False
readout: weighted_feature
# [weighted_feature, task_aware_attention]
# 这些都是EQGAT需要的参数，之后优化掉
cross_ablate: False
no_feat_attn: False
precision: 16

#Dataset Settings
drop_last: False
run_name: hemenet
train_task: multi
train_split: train_all
val_split: val
test_split: test
alpha_only: False
offset_strategy: 1
num_workers: 0

# Trainer Settings
device: 
  - 2
nruns: 3
wandb: True
save_dir: hemenet
gradient_clip_val: 10
load_ckpt: null
seed: 817