# This is the config file for GearNet without Edge layers and Checkpoints.

# Lightning Model Settings
model_args:
  sdim: 128
  vdim: 16
  depth: 3
  aggr: 'mean'
  task: multi
  model_type: gearnet
  num_radial: 32
  learning_rate: 1.0e-4
  weight_decay: 0
  readout: vallina
  # [vallina, weighted_feature, task_aware_attention]
  r_cutoff: 4.5
  factor_scheduler: 0.75
  layer_norm: True
  batch_norm: True
  hidden_dims:
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
  embedding_dim: 512
  num_relation: 6

#Dataset Settings
batch_size: 64
drop_last: False
run_name: gearnet
train_split: train_all
val_split: val
test_split: test
alpha_only: True
offset_strategy: 1
num_workers: 4
graph_cache_dir: ./datasets/MultiTask_c03_id09/graphs_new/hetero_alphaonly_knn5_spatial4.5_sequential2

# Trainer Settings
device:
  - 0
  - 1
nruns: 3
wandb: True
save_dir: gearnet
gradient_clip_val: 10
precision: 16
load_ckpt: null
seed: 817
batch_accum_grad: 1
max_epochs: 30